// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrlnOmr6JG7idnPfPCiu_k_CCR_xCZOLw',
    appId: '1:509489973435:web:e7434f92bcbc3e4432419e',
    messagingSenderId: '509489973435',
    projectId: 'retailiq-63912',
    authDomain: 'retailiq-63912.firebaseapp.com',
    storageBucket: 'retailiq-63912.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmjErxEcAc_3elDKmMvWUgy50VlecqmYo',
    appId: '1:509489973435:android:a70efff964c4fb3332419e',
    messagingSenderId: '509489973435',
    projectId: 'retailiq-63912',
    storageBucket: 'retailiq-63912.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYSosPvV7m_gpYZBzBuk237udLH4INS5I',
    appId: '1:509489973435:ios:262c74d9c65adbbb32419e',
    messagingSenderId: '509489973435',
    projectId: 'retailiq-63912',
    storageBucket: 'retailiq-63912.firebasestorage.app',
    iosBundleId: 'com.retailiq.retailIq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYSosPvV7m_gpYZBzBuk237udLH4INS5I',
    appId: '1:509489973435:ios:262c74d9c65adbbb32419e',
    messagingSenderId: '509489973435',
    projectId: 'retailiq-63912',
    storageBucket: 'retailiq-63912.firebasestorage.app',
    iosBundleId: 'com.retailiq.retailIq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrlnOmr6JG7idnPfPCiu_k_CCR_xCZOLw',
    appId: '1:509489973435:web:92e11c7527c9960a32419e',
    messagingSenderId: '509489973435',
    projectId: 'retailiq-63912',
    authDomain: 'retailiq-63912.firebaseapp.com',
    storageBucket: 'retailiq-63912.firebasestorage.app',
  );
}
